<nav class="menu" id="activity">
<a href="swimming.html">&nbsp;Swimming</a>
<a href="tennis.html">&nbsp;Tennis</a>
<a href="softball.html">&nbsp;Softball</a>
<a href="dancing.html">&nbsp;Dancing</a>
<a href="yoga.html">&nbsp;Yoga</a>
</nav>
<nav class="menu" id="location">
<a href="akron.html">&nbsp;Akron</a>
<a href="cleveland.html">&nbsp;Cleveland</a>
<a href="columbus.html">&nbsp;Columbus</a>
<a href="kent.html">&nbsp;Kent</a>
</nav>

